# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-13 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=50)),
                ('artist', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('bio', models.TextField(max_length=255)),
            ],
        ),
    ]
